name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Build React frontend
      - name: Install dependencies & Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          tar -czf build.tar.gz build

      # Build Express backend
      - name: Install dependencies backend
        run: |
          cd backend
          npm install
